name: Deploy apps

on:
    workflow_dispatch:

jobs:
    enviroment:
        DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
        
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to server
              run: docker compose up -d --builds